name: "Neolink 0.6.1 based on dm82m hassio-addons 0.0.8"
description: "Will run Neolink directly as Add-on in HAOS"
version: "0.0.8"
slug: "neolink"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - i386
  - armv7
ports:
  8554/tcp: 8554
map:
  - config
options:
  mode: rtsp
  log: info
schema:
  mode: list(rtsp|mqtt|dual)
  log: list(info|warn|error|debug)
